//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btprox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("btprox.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t lock (only run the command).
        /// </summary>
        internal static string dontLock {
            get {
                return ResourceManager.GetString("dontLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string exitButton {
            get {
                return ResourceManager.GetString("exitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide.
        /// </summary>
        internal static string hideButton {
            get {
                return ResourceManager.GetString("hideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments:.
        /// </summary>
        internal static string labelArguments {
            get {
                return ResourceManager.GetString("labelArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock command:.
        /// </summary>
        internal static string labelLockCommand {
            get {
                return ResourceManager.GetString("labelLockCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string labelMinutes {
            get {
                return ResourceManager.GetString("labelMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release command:.
        /// </summary>
        internal static string labelReleaseCommand {
            get {
                return ResourceManager.GetString("labelReleaseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout:.
        /// </summary>
        internal static string labelTimeout {
            get {
                return ResourceManager.GetString("labelTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string labelUnknown {
            get {
                return ResourceManager.GetString("labelUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used device:.
        /// </summary>
        internal static string labelUsedDevice {
            get {
                return ResourceManager.GetString("labelUsedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the program in order to complete settings change..
        /// </summary>
        internal static string languageWarning {
            get {
                return ResourceManager.GetString("languageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort pending lock.
        /// </summary>
        internal static string menuItemAbortLock {
            get {
                return ResourceManager.GetString("menuItemAbortLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string menuItemAbout {
            get {
                return ResourceManager.GetString("menuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string menuItemExit {
            get {
                return ResourceManager.GetString("menuItemExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string menuItemRestore {
            get {
                return ResourceManager.GetString("menuItemRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string menuOptions {
            get {
                return ResourceManager.GetString("menuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted workstation lock.
        /// </summary>
        internal static string messageAbortedLock {
            get {
                return ResourceManager.GetString("messageAbortedLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device appeared.
        /// </summary>
        internal static string messageDeviceAppeared {
            get {
                return ResourceManager.GetString("messageDeviceAppeared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device disappeared.
        /// </summary>
        internal static string messageDeviceDisappeared {
            get {
                return ResourceManager.GetString("messageDeviceDisappeared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device found.
        /// </summary>
        internal static string messageDeviceFound {
            get {
                return ResourceManager.GetString("messageDeviceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device in range.
        /// </summary>
        internal static string messageDeviceInRange {
            get {
                return ResourceManager.GetString("messageDeviceInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} in range.
        /// </summary>
        internal static string messageDeviceInRangeName {
            get {
                return ResourceManager.GetString("messageDeviceInRangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking workstation.
        /// </summary>
        internal static string messageLocking {
            get {
                return ResourceManager.GetString("messageLocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking workstation in {0} minutes.
        /// </summary>
        internal static string messageLockingInMin {
            get {
                return ResourceManager.GetString("messageLockingInMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locking workstation in {0} seconds.
        /// </summary>
        internal static string messageLockingInSec {
            get {
                return ResourceManager.GetString("messageLockingInSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes to lock.
        /// </summary>
        internal static string messageMinutesToLock {
            get {
                return ResourceManager.GetString("messageMinutesToLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select device first.
        /// </summary>
        internal static string messageSelectDevice {
            get {
                return ResourceManager.GetString("messageSelectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string messageStarted {
            get {
                return ResourceManager.GetString("messageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string messageStopped {
            get {
                return ResourceManager.GetString("messageStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping.
        /// </summary>
        internal static string messageStopping {
            get {
                return ResourceManager.GetString("messageStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for device.
        /// </summary>
        internal static string messageWaitingForDevice {
            get {
                return ResourceManager.GetString("messageWaitingForDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string optionLabelSeconds {
            get {
                return ResourceManager.GetString("optionLabelSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string optionLanguage {
            get {
                return ResourceManager.GetString("optionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan period:.
        /// </summary>
        internal static string optionScanPeriod {
            get {
                return ResourceManager.GetString("optionScanPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string optionSeconds {
            get {
                return ResourceManager.GetString("optionSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound enabled.
        /// </summary>
        internal static string optionSoundEnabled {
            get {
                return ResourceManager.GetString("optionSoundEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Notification Balloons.
        /// </summary>
        internal static string optionsShowBaloons {
            get {
                return ResourceManager.GetString("optionsShowBaloons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string optionTabtext {
            get {
                return ResourceManager.GetString("optionTabtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string optionTitle {
            get {
                return ResourceManager.GetString("optionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string saveButton {
            get {
                return ResourceManager.GetString("saveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start.
        /// </summary>
        internal static string startButton {
            get {
                return ResourceManager.GetString("startButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;top.
        /// </summary>
        internal static string stopButton {
            get {
                return ResourceManager.GetString("stopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program locks the workstation when connected bluetooth device disappears for specified time. 32feet.NET library is used for devices discovery: http://inthehand.com/content/32feet.aspx. Icons from http://commons.wikimedia.org/wiki/Crystal_Clear
        ///Used command line analyzer from http://www.codeproject.com/KB/recipes/command_line.aspx.
        /// </summary>
        internal static string textAbout {
            get {
                return ResourceManager.GetString("textAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Log.
        /// </summary>
        internal static string useWindowsLog {
            get {
                return ResourceManager.GetString("useWindowsLog", resourceCulture);
            }
        }
    }
}
